version: '3'

services:
  jupyter_lab:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter lab --ip=0.0.0.0 --port=9999 --notebook-dir=/data --allow-root --NotebookApp.token=BioinfErasmus123
    volumes:
    - ./:/data
    restart: unless-stopped
    ports:
    - "9999:9999"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
